backend:
  name: github
  repo: fabianklonsdorf/carbon-cms


media_folder: src/images
public_folder: /images

collections:
  - name: blog
    label: Blog
    extension: mdx
    format: frontmatter
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - label: "Navigation"
    name: "navigation"
    extension: yaml
    format: yaml
    files:
      - label: "Left Navigation"
        name: "left-navigation"
        file: "src/data/nav-items.yaml"
        fields:
          - { name: body, label: Body, widget: markdown }