backend:
  name: github
  repo: fabianklonsdorf/carbon-cms


media_folder: static/assets
public_folder: /assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    fields:
      - { name: path, label: Path }
      - { name: date, label: Date, widget: datetime }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
  - label: "Navigation"
    name: "navigation"
    extension: "yaml"
    format: "yaml"
    files:
      - label: "Left Navigation"
        name: "left-navigation"
        file: "src/data/nav-items-1.yaml"
        fields:
          - { label: Body, widget: markdown }